name: GhanabeSomething
favicon: null
layout_spectrum: 0.30347829358652234
typography_spectrum: 0.4434151821769774
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d4e3ce'
    - '#250e2a'
    - '#524562'
    - '#9b1d19'
    - '#d98a36'
  brandStrength: 0.4269420597702265
  lightness: 0.6150318586733192
  saturation: 0.3932404809165746
  rhythmicContrast: 0.7409908999688923
purpose: []
